listen:
  - edition: bedrock
    host: 0.0.0.0
    port: 21000
    versions:
      - v1.19.20.23
  - host: 0.0.0.0
    port: 22000
    edition: bedrock

connect:
  edition: bedrock
  host: 127.0.0.1
  port: 20000
  version: v1.19.20.23

